test: main.c frequencyList.c helpers.c nodeQueue.c
	gcc main.c frequencyList.c helpers.c nodeQueue.c -o test



final: finalMain.c linkedList.c frequencyList.c helpers.c nodeQueue.c
	gcc finalMain.c linkedList.c frequencyList.c helpers.c nodeQueue.c -o exeFinal

list: listMain.c linkedList.c frequencyList.c helpers.c nodeQueue.c
	gcc listMain.c linkedList.c frequencyList.c helpers.c nodeQueue.c -o listExe


