test: main.c frequencyList.c helpers.c nodeQueue.c
	gcc main.c frequencyList.c helpers.c nodeQueue.c -o test



final: finalMain.c frequencyList.c helpers.c nodeQueue.c
	gcc finalMain.c frequencyList.c helpers.c nodeQueue.c -o exeFinal

